### ISSUE TITLE
box format

### ISSUE THREAD

**Issue by rbgreenway** [developer0hye/Modern-Cpp-NMS#2]
In your nms code, your comments say that the box format is: x1, y1, x2, y2, score, label
From my testing, it is actually: x1, y1, width, height, score, label
This format follows the Yolo detection box standard.  Otherwise, your code seems to work fine and is very clean.

UPDATE:  I had an index wrong.  The box format is x1,y1,x2,y2,score,label
Sorry1

**Comment by rbgreenway** [comment]
My mistake.

**Comment by developer0hye** [comment]
@rbgreenway 
Good!
